### PR TITLE
feat: add artyop ci-structure & helm reviewers

### PR DESCRIPTION
**Pull request by Artyop**
Adding myself to ci-structure and helm reviewer teams.

### CODE REVIEW

**Comment by Artyop** [comment]
@cilium/ci-structure @cilium/helm kind ping for review please

**Review by viktor-kurchenko — APPROVED** [review]

**Review by gandro — APPROVED** [review]
ACK for Helm!

**Comment by michi-covalent** [comment]
let's wait for a committer approval from the ci-structure team 🚀🙏

**Review by sayboras — APPROVED** [review]
ACK for ci-structure

**Pull request merged**
