### PR TITLE
Add DamianSawicki to organization members

### PR DESCRIPTION
**Pull request by DamianSawicki**
Add Damian Sawicki (@DamianSawicki) to org members to make it easier to test future (and ongoing) PRs.  [Contributions to date](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3ADamianSawicki).

### CODE REVIEW

**Comment by DamianSawicki** [comment]
/cc @joamaki

FYI @ovidiutirla @kl52752 @robscott @bowei

**Comment by xmulligan** [comment]
General +1 here, can you just put it in alphabetical order?

**Comment by DamianSawicki** [comment]
> General +1 here, can you just put it in alphabetical order?

Thanks! I believe the order in this file is first capitalized, then non-capitalized, both alphabetically. Since most people's handles are non-capitalized, my handle starting with `D` turned out to be the smallest alphabetically among the capitalized ones.

@xmulligan Would you like me to sort the entire thing ignoring the distinction into capitalized and non-capitalized?

**Comment by pchaigno** [comment]
> @xmulligan Would you like me to sort the entire thing ignoring the distinction into capitalized and non-capitalized?

No, it's good as is. What we'd need is a linter :smile_cat:

**Comment by xmulligan** [comment]
Wow, sorry totally missed that 😅  You are correct, please leave it as is

**Review by xmulligan — APPROVED** [review]

**Review by ovidiutirla — APPROVED** [review]
🚀

**Review by joestringer — APPROVED** [review]

**Pull request merged**
