### PR TITLE
Request to add dlapcevic to sig-scalability

### PR DESCRIPTION
**Pull request by dlapcevic**
I've been working on Cilium scalability, mostly related to network policies:
- https://github.com/cilium/cilium/issues/31457
- https://github.com/cilium/cilium/issues/33360

I want to and think it would be good to get involved more in the development of these areas.

### CODE REVIEW

**Comment by dlapcevic** [comment]
@marseel @joestringer

**Comment by joestringer** [comment]
cc @cilium/sig-scalability currently owns these areas:

```
$ git grep sig-scalability CODEOWNERS
CODEOWNERS:# - @cilium/sig-scalability:
CODEOWNERS:/.github/actions/cl2-modules/ @cilium/sig-scalability
CODEOWNERS:/.github/workflows/*scale*.yaml @cilium/sig-scalability @cilium/github-sec @cilium/ci-structure
CODEOWNERS:/.github/workflows/*perf*.yaml @cilium/sig-scalability @cilium/github-sec @cilium/ci-structure
CODEOWNERS:/operator/pkg/ciliumendpointslice @cilium/sig-scalability
```

I can see from your PRs that you have been heavily involved in CES work. It also wouldn't hurt to have more owners on those workflow areas. 

https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Adlapcevic++is%3Amerged+

Assuming that you are willing to adhere to the [responsibilities of a reviewer](https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#reviewer) and the folks in @cilium/sig-scalability can speak to the qualifications aspect, it would be great to have your input as a member of this group :clap:

**Comment by marseel** [comment]
Looking forward to it, also in the context of the current scale-testing we perform as I know you have quite a lot of experience with CL2 :)

**Comment by dlapcevic** [comment]
Yes, I accept the responsibilities of a reviewer, and I'm looking forward to being part of the team that works on the scalability of Cilium.

**Review by pchaigno — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
