### PR TITLE
Request to add learnitall to metrics role

### PR DESCRIPTION
**Pull request by learnitall**
Hello! In the next couple of months, I've been tasked with working on some of the issues that we've been facing with metric stability and maturity. I'm planning on writing a CFP to propose a couple of new aspects for metric management. Some example issues that I'm hoping to address are:

* https://github.com/cilium/cilium/issues/27659
* https://github.com/cilium/cilium/issues/34521
* https://github.com/cilium/cilium/issues/27057
* https://github.com/cilium/cilium/issues/33995

Thanks!

### CODE REVIEW

**Comment by joestringer** [comment]
cc @cilium/metrics

**Comment by chancez** [comment]
This feels reasonable to me. We definitely need a few more members on the metrics team in general

**Comment by tommyp1ckles** [comment]
I think @learnitall would be a great addition to sig-metrics.

**Review by michi-covalent — APPROVED** [review]
🚀

**Comment by learnitall** [comment]
Thanks all!

**Pull request merged**
