### PR TITLE
Request to add dlapcevic to sig-policy

### PR DESCRIPTION
**Pull request by dlapcevic**
I've been working on Cilium scalability, mostly related to network policies:
- https://github.com/cilium/cilium/issues/31457
- https://github.com/cilium/cilium/issues/33360

I want to and think it would be good to get involved more in the development of these areas.

### CODE REVIEW

**Comment by dlapcevic** [comment]
@squeed @joestringer

**Comment by joestringer** [comment]
cc @cilium/sig-policy currently owns these areas:

```
$ git grep sig-policy CODEOWNERS
CODEOWNERS:# - @cilium/sig-policy:
CODEOWNERS:/daemon/cmd/policy* @cilium/sig-policy
CODEOWNERS:/Documentation/observability/ @cilium/sig-policy @cilium/docs-structure
CODEOWNERS:/Documentation/security/http.rst @cilium/sig-policy @cilium/docs-structure
CODEOWNERS:/Documentation/security/policy-creation.rst @cilium/sig-policy @cilium/docs-structure
CODEOWNERS:/Documentation/security/policy/ @cilium/sig-policy @cilium/docs-structure
CODEOWNERS:/operator/pkg/networkpolicy @cilium/sig-policy
CODEOWNERS:/pkg/container/bitlpm/ @cilium/ipcache @cilium/sig-policy
CODEOWNERS:/pkg/crypto/ @cilium/sig-hubble @cilium/sig-policy
CODEOWNERS:/pkg/identity @cilium/sig-policy
CODEOWNERS:/pkg/labels @cilium/sig-policy @cilium/api
CODEOWNERS:/pkg/labelsfilter @cilium/sig-policy
CODEOWNERS:/pkg/policy @cilium/sig-policy
CODEOWNERS:/pkg/policy/groups/aws/ @cilium/sig-policy @cilium/aws
CODEOWNERS:/pkg/policy/k8s @cilium/sig-policy
CODEOWNERS:/test/k8s/net_policies.go @cilium/sig-policy @cilium/ci-structure
CODEOWNERS:/test/runtime/net_policies.go @cilium/sig-policy @cilium/ci-structure
```

Have you been contributing in these areas? It's not immediately apparent to me from your PR submissions: https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Adlapcevic++is%3Amerged+ . The reason I ask is related to the in-depth knowledge expectations as part of the [reviewer requirements](https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#reviewer) for this area. Policy is a particularly tricky aspect of Cilium, so it'd be good to ensure that both (a) we continue to ensure the high quality bar of changes and review in this area, as well as (b) we make sure that there is a path for contributors like yourself to help maintain this code.

**Comment by dlapcevic** [comment]
You are right. My contributions were mostly CES related.
CES is part of the network policy enforcement system, as is my more recent work of operator managing identities (https://github.com/cilium/cilium/issues/27752).

I agree with you that this is no sufficient evidence, so I would be grateful if you could suggest how I could proceed.

**Comment by joestringer** [comment]
Ah I see where you're coming from. My initial thought when looking at the responsibilities of @cilium/sig-policy is the bread-and-butter of policy enforcement, ranging from policy APIs, the BPF map representation of policy, how policy computation and calculation occurs. You can see the expected responsibilities for this codeowner [here](https://docs.cilium.io/en/latest/contributing/development/reviewers_committers/review_process/#cilium-internals). Identity allocation pieces typically do not change much at all, but this team is the best positioned to have the expertise to understand the implications of any changes to identity. Hence `pkg/identity` currently falls under that group. And indeed while policy relies on the CEP/CES state propagation to ensure correct enforcement, my gut feeling is that the folks in @cilium/sig-k8s or @cilium/sig-scalability tend to be more involved in thinking about the details of CEP/CES.

If you plan on working on direct network policy calculation/computation logic, then I think there's alignment within this codeowner and we can figure out how to support your efforts there. You can get a sense for the sorts of changes you would be expected to review in [this list](https://github.com/cilium/cilium/pulls?q=is%3Apr+label%3Asig%2Fpolicy). On the other hand if you're primarily interested in just the allocation pieces, then we probably want to figure out another path.

No codeowners division of responsibilities is perfect, figuring these out is more of an art than a science. We'd like a good mix of expertise and general interest while keeping the door open to new contributors. Primarily these codeowner groups are also taking care of ongoing change within an area, including reviewing others' PRs and improving the implementation. If we anticipate that the identity allocation pieces are likely to continue to change and iterate over time then it might make sense to split the ownership for pkg/identity from @cilium/sig-policy . Splitting up the ownership could involve either creating another codeowner group or alternatively identifying the key codepaths that are related to this and moving it over to a more appropriate existing codeowner (and provide a path for you to help with review in that area too).

**Comment by marseel** [comment]
> No codeowners division of responsibilities is perfect, figuring these out is more of an art than a science. We'd like a good mix of expertise and general interest while keeping the door open to new contributors.
[...]

I personally think this is a problem that can be solved differently. In K8s it was solved with per-directory ownership [example](https://github.com/kubernetes/kubernetes/blob/master/cmd/yamlfmt/OWNERS). Essentially you contribute to a specific area - for example, the identity package, you get the owner for this directory. Once you gather more coverage across different directories that belong to a specific team, you can join that team. But this would require a whole revamp of current ownership managed by GitHub and probably replacing with prow-based automation.

**Comment by pchaigno** [comment]
@dlapcevic Looking at the pull requests implementing https://github.com/cilium/cilium/issues/27752, they all required reviews from cilium/operator (more than cilium/sig-policy). Given the goal of this work stream, it makes sense that the operator code base would be the most impacted. I'm surprised that isn't the team you want to join :slightly_smiling_face: 

For reference, cilium/operator is responsible for the following code paths:
```
$ git grep cilium/operator CODEOWNERS
CODEOWNERS:# - @cilium/operator:
CODEOWNERS:/api/v1/operator/ @cilium/api @cilium/operator
CODEOWNERS:/Documentation/internals/cilium_operator.rst @cilium/operator @cilium/docs-structure
CODEOWNERS:/operator/ @cilium/operator
CODEOWNERS:/pkg/ipam/allocator/clusterpool/ @cilium/sig-ipam @cilium/operator
```

**Comment by dlapcevic** [comment]
@pchaigno you're right. I opened up a PR for that, and I'll close this.

https://github.com/cilium/community/pull/141

**Pull request closed without merging**
