### PR TITLE
add rectified95 to new hubble-metrics group

### PR DESCRIPTION
**Pull request by rectified95**
Listing new sig for the metrics portion of Hubble and adding myself as reviewer.
Related contributions: https://github.com/cilium/cilium/pulls/rectified95

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
LGTM from my perspective, but it would be good for at least one or two members of @cilium/sig-hubble to also approve.

cc @chancez @gandro @genbit @glibsm @jrfastab @kaworu @michi-covalent @rolinh @tklauser you are all part of @cilium/sig-hubble currently, but you may / may not be in this list. If you want to be in this group, please voice up. If you are wondering why I am pinging you, you may want to grep for your username in this repository and check whether your teams reflect your current interests for contribution within the project.

**Review by rolinh — COMMENTED** [review]
I think a Hubble metrics group overall makes sense to me. Generally speaking, I'm not opposed to breaking down the Hubble subsystem into groups with a more narrow scope and a Hubble metrics group is definitely one of the first candidate that comes to mind.

As of note, Hubble metrics are currently covered by the sig-hubble-api group as well with the idea that we want some overall consistency in metrics and not do breaking changes without careful considerations. Therefore, if we are to create this new group, I would require to define the responsibilities for reviewers clearly and remove the sig-hubble-api group as a codeowner for Hubble metrics.

**Review by kaworu — CHANGES_REQUESTED** [review]
Agree with @rolinh wrote, and if we create a hubble metrics group then I'd like to be taken off it if there is enough people already.

**Comment by rectified95** [comment]
Please let me know if this list is complete, I made it based on who I saw reviewing my metrics-related PRs.
After removing `kaworu`, it'll be:
```
members:
- chancez
- gandro
- rectified95
- rolinh
```

**Review by gandro — APPROVED** [review]

**Review by glibsm — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

**Review by chancez — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by joestringer** [comment]
I plan to get this all synced up early next week.

**Pull request merged**
