### PR TITLE
Remove Varun Marupadi from Cilium Security

### PR DESCRIPTION
**Pull request by ferozsalam**
Varun has opted to step down from the team.

### CODE REVIEW

**Comment by ferozsalam** [comment]
@varunmar – Hi Varun, pinging you here to confirm that you are OK with this change, cc @joestringer as well

**Review by joestringer — APPROVED** [review]
Varun had reached out to me to step down from active Cilium duties earlier this year. We can give it a few days for his response, but if there is no response then I think that's fine and we can go ahead and merge this.

**Comment by xmulligan** [comment]
One other thing, rather than just removing him. What do you think about creating an emeritus section similar to what we have on https://github.com/cilium/cilium/blob/main/MAINTAINERS.md#cilium--hubble-emeritus-committers?

**Comment by joestringer** [comment]
I'm open to that idea, though historically we've only tracked emeritus members for the committers group, not any of the other roles.

**Pull request merged**
