### PR TITLE
SIG-BGP Team: Adds danehans

### PR DESCRIPTION
**Pull request by danehans**
I have been an [active contributor](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Adanehans+) and [org member](https://github.com/cilium/community/blob/main/ladder/members.yaml) for the past 5 months with a focus on BGP Control Plane. I intend on continuing in this role and would like to be part of the `SIG-BGP` team.

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
IIUC, this is a process of becoming a `reviewer`: https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#reviewer

**Comment by danehans** [comment]
Thank you @YutaroHayakawa @joestringer

**Comment by YutaroHayakawa** [comment]
How can we get this merged? @joestringer @xmulligan

**Comment by xmulligan** [comment]
Sorry was on vacation. @joestringer needs to set it up on the backend

**Pull request merged**
